version: '2'

services:
    web:
        build: ./nginx
        ports:
            - '80:80'
        volumes:
            - ./code:/code:rw
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - magento-network
        links:
            - php
    php:
        build: ./php-fpm
        volumes:
            - ./code:/code:rw
        networks:
            - magento-network
        links:
            - db
    db:
      image: mysql
      volumes:
        - /mysql/magento:/var/lib/mysql
      ports:
        - '3308:3306'
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=magento
      restart: always
      networks:
          - magento-network

networks:
    magento-network:
        driver: bridge
